package org.akvo.flow.telnet;

//** TODO: separate new Socket, add more functionality and copyright headers
import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ConnectException;
import java.net.Socket;

public class Telnet implements Closeable
{
	private Socket socket;
	private BufferedReader in;
	private PrintWriter out;

	/**
	 * Establishes a connection through the telnet command to target host
	 * 
	 * @param ip
	 *            of target
	 * @param port
	 * @param retries
	 *            before giving up and ending connection
	 * @throws IOException
	 * @throws InterruptedException
	 */
	public Telnet(String ip, int port, int retries) throws IOException, InterruptedException
	{
		System.out.println("Connecting to " + ip + " (port: " + port + ")");

		int attempt = 1;
		while (true)
		{
			if (attempt > retries)
			{
				throw new ConnectException("Telnet failed to connect. Check your address and make sure emulator is running");
			}
			try
			{
				socket = new Socket(ip, port);
			}
			catch (ConnectException e)
			{
				System.err.println("attempt #" + attempt + " failed: " + e.getMessage());
				attempt++;
				Thread.sleep(500);
				continue;
			}
			break;
		}

		System.out.println("Telnet sucessfully connected");

		in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
		out = new PrintWriter(socket.getOutputStream());
	}

	/**
	 * Sends a string without expecting a response
	 * 
	 * @param text
	 */
	public void send(String text)
	{
		out.write(text);
		out.write('\n');
		out.flush();
	}

	/**
	 * Receive welcome message when initially connecting to the telnet
	 * 
	 * @return {@link TelnetResponse} representing welcome message
	 * @throws IOException
	 */
	public TelnetResponse receive() throws IOException
	{
		return new TelnetResponse(in);
	}

	/**
	 * Sends a string to be read and returns a {@link TelnetResponse} object
	 * 
	 * @param text
	 *            to be input to console
	 * @return {@link TelnetResponse} generated by input
	 * @throws IOException
	 */
	public TelnetResponse communicate(String text) throws IOException
	{
		// send
		send(text);
		// receive
		return receive();
	}

	@Override
	public void close() throws IOException
	{
		System.out.println("Telnet disconnecting");
		socket.close();
	}
}
